var ToogleSupport=function(){Array.prototype.forEach.call(document.querySelectorAll(".nav-toggle"),function(a){a.addEventListener("click",function(){toggleClick(this)})})},toggleClick=function(a){a.classList.toggle("is-active");Array.prototype.forEach.call(a.parentNode.querySelectorAll(".nav-menu"),function(a){a.classList.toggle("is-active")})},StickyBar=function(){var a=0,c=!1,b=document.getElementById("menu-top"),e=document.getElementById("menu-bar");return function(){var d=window.pageYOffset||
document.scrollTop||document.documentElement.scrollTop||document.body.scrollTop;d>=window.innerHeight!==c&&(document.body.classList.toggle("fix"),c=!c,a=0);c?e.classList.contains("is-active")&&(0===a?a=d:50<=Math.abs(d-a)&&(toggleClick(e),a=0)):b.classList.contains("is-active")?0===a?a=d:50<=Math.abs(d-a)&&(toggleClick(b),a=0):a=0}}(),GMapHack=function(){Array.prototype.forEach.call(document.getElementsByClassName("gmap"),function(a){var c=a.parentNode;a.classList.add("scrollOff");c.addEventListener("click",
function(){a.classList.remove("scrollOff")});c.addEventListener("mouseleave",function(){a.classList.add("scrollOff")})})},EnancheForm=function(){var a=function(){var a=new ComboDate("arrival"),b=new ComboDate("departure"),e=document.getElementById("arrival_error"),d=document.getElementById("departure_error");return function(){var c=a.isValid(),g=b.isValid();c&&g&&a.getValue()>=b.getValue()&&a.setError('you are supposed to "arrive" before "leaving"');10==a.getValueString().length&&(e.innerHTML=a.getError());
10==b.getValueString().length&&(d.innerHTML=b.getError())}}();document.getElementById("arrival").addEventListener("change",a);document.getElementById("departure").addEventListener("change",a)},BindAccomodation=function(){var a=document.getElementById("kind"),c=document.getElementById("resource"),b=document.querySelectorAll("#resource optgroup");a.addEventListener("change",function(){Array.prototype.forEach.call(b,function(b){b.style.display=b.dataset.kind==a.value?"":"none";b.disabled=b.dataset.kind!=
a.value;b.dataset.kind==a.value&&(c.value=b.children[0].value)})})},fireEvent=function(a,c){if(void 0!==a)if("createEvent"in document){var b=document.createEvent("HTMLEvents");b.initEvent(c,!1,!0);a.dispatchEvent(b)}else a.fireEvent(c)},parseGet=function(a){for(var c,b,e=location.search.substr(1).split("&"),d=0;d<e.length;d++)b=e[d].split("="),b[0]===a&&(c=decodeURIComponent(b[1]));return c},cardChange=function(){var a=document.getElementById("card"),c=document.getElementById("kind");return function(){var b=
a.querySelectorAll("option[value="+a.value+"]"),b=0===b.length?void 0:b[0];if(void 0!==b&&b.dataset.only){for(var e=c.querySelectorAll("option[value="+c.value+"]"),b=b.dataset.only.split(","),d=0;d<c.children.length;d++){for(var f=!1,g=0;g<b.length;g++)f=f||c.children[d].value===b[g];c.children[d].style.display=f?"":"none";c.children[d].disabled=!f}if(e.length){e=e[0];e=e.parentNode.dataset.kind;d=!1;for(f=0;f<b.length;f++)d=d||e===b[f];d||(c.value=c.querySelectorAll("option[value="+b[0]+"]")[0].value,
fireEvent(c,"change"))}}else for(b=0;b<c.children.length;b++)c.children[b].style.display="",c.children[b].disabled=!1}}(),SetFromQuery=function(){var a=parseGet("pitch");if(void 0!==a){var c=document.getElementById("kind");c.value=a;fireEvent(c,"change")}var c=parseGet("promotion"),a=document.getElementById("card"),b;a.addEventListener("change",cardChange);void 0!==c&&(b=a.querySelectorAll("option[data-id="+c+"]"),0===b.length?b=void 0:(b=b[0],a.value=b.value,fireEvent(a,"change")));for(c=0;c<a.children.length;c++){var e=
a.children[c];if("always"!==e.dataset.show){for(var d=0;d<e.children.length;d++){var f=e.children[d];"always"!==f.dataset.show&&f!==b&&(e.removeChild(f),d--)}0===e.children.length&&(a.removeChild(e),c--)}}},ModalSupport=function(){var a=function(a,b){var c=new XMLHttpRequest;c.open("GET",a,!0);c.onload=function(){200<=c.status&&400>c.status&&b(c.responseText);console.error(c.status)};c.onerror=function(){console.error(c.status)};c.send()},c=document.getElementsByClassName("modal")[0],b=document.getElementsByClassName("modal-card-title")[0],
e=document.getElementsByClassName("modal-card-body")[0];Array.prototype.forEach.call(document.querySelectorAll("a[data-modal]"),function(d){d.addEventListener("click",function(d){d.preventDefault();b.innerHTML=this.dataset.modal;a(this.href,function(a){e.innerHTML=a;c.classList.add("is-active")});ga("send","event","modal","open",this.href)})});Array.prototype.forEach.call(document.querySelectorAll("[data-close-modal],.modal-background"),function(a){a.addEventListener("click",function(a){a.preventDefault();
c.classList.remove("is-active")})})},SectionChange=function(){var a=document.getElementById("menu-desktop"),c=document.getElementById("menu-mobile");return function(b,e){if(b){var d=a.getElementsByClassName("is-active");0<d.length&&d[0].classList.remove("is-active");d=a.querySelectorAll('a[href="#'+b+'"]');0<d.length&&d[0].parentNode.classList.add("is-active");d=c.getElementsByClassName("is-active");0<d.length&&d[0].classList.remove("is-active");d=c.querySelectorAll('a[href="#'+b+'"]');0<d.length&&
d[0].classList.add("is-active");ga("send","event","section","read",e?e:b)}}}(),SectionHandler=function(){var a=[];Array.prototype.forEach.call(document.querySelectorAll("section"),function(b){a.push({id:b.id,top:b.offsetTop,gaid:b.dataset.gaid})});a.sort(function(a,c){return a.top-c.top});var c;window.addEventListener("scroll",function(){for(var b=window.pageYOffset||document.scrollTop||document.documentElement.scrollTop||document.body.scrollTop,b=b+window.innerHeight/3,e=0,d=1;!(a[e].top<=b&&b<a[d].top)&&
d!==a.length-1;)e=d,d+=1;b=a[e];b.id!==c&&(c=b.id,SectionChange(b.id,b.gaid))})},LifeAnimation=function(){window.pause=!1;window.carousellCallback=void 0;var a=document.querySelectorAll('a[data-carousell="play"]')[0];a&&a.addEventListener("click",function(){this.classList.toggle("non-active");this.nextElementSibling.classList.toggle("non-active");c(!1,!1)});(a=document.querySelectorAll('a[data-carousell="pause"]')[0])&&a.addEventListener("click",function(){this.classList.toggle("non-active");this.previousElementSibling.classList.toggle("non-active");
window.clearTimeout(window.carousellCallback)});document.querySelectorAll('a[data-carousell="next"]')[0].addEventListener("click",function(){window.clearTimeout(window.carousellCallback);c(!1,!0)});document.querySelectorAll('a[data-carousell="back"]')[0].addEventListener("click",function(){window.clearTimeout(window.carousellCallback);c(!0,!0)});document.querySelector('[data-gaid="highlights"]').addEventListener("click",function(){window.clearTimeout(window.carousellCallback)});var c=function(a,e){var b=
document.querySelectorAll(".carousell .is-active")[0];b.classList.remove("is-active");var f=b.dataset.ref;f&&document.getElementById(f).classList.remove("is-active");do a?(f=b.previousElementSibling)||(f=b.parentNode.children[b.parentNode.children.length-1]):(f=b.nextElementSibling)||(f=b.parentNode.children[0]),b=f;while(!f.classList.contains("carousell-item"));f.classList.add("is-active");(b=f.dataset.ref)&&document.getElementById(b).classList.add("is-active");e||(window.carousellCallback=setTimeout(c,
5E3))};c()},BindExtraAnalitycs=function(){Array.prototype.forEach.call(document.querySelectorAll('a[href="mailto:info@campingpuntaindiani.it"]'),function(a){a.addEventListener("click",function(){ga("send","event","mail","click",this.href)})})},BindNews=function(){var a=document.getElementById("close-news");a&&a.addEventListener("click",function(){var a=document.getElementById("news");a&&(a.style.display="none")})};
(function(){document.body.classList.remove("nojs");window.addEventListener("scroll",StickyBar);StickyBar();ToogleSupport();GMapHack();EnancheForm();BindAccomodation();SetFromQuery();ModalSupport();SectionHandler();LifeAnimation();BindExtraAnalitycs();BindNews()})();
